spring.application.name=Assignment1

openai.api.key=${OPENAI_API_KEY}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# use virtual threads for handling HTTP requests, so Tomcat isn't limited to ~200 threads
spring.threads.virtual.enabled=true